apiVersion : apps/v1
kind: Deployment
metadata:
  name: chandrikarevhirejob 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chandrikarevhirejob
  template:
    metadata:
      labels:
        app: chandrikarevhirejob 
    spec:
      containers:
        - name: chandrikarevhirejob 
          image: revhireacrchandu2001.azurecr.io/chandrikarevhirejob
          ports:
          - containerPort: 8000